#!/usr/bin/env python

import os

path = os.path.abspath('.') 

def get_mode(intcode, i, mode1, mode2):
    # how args would be handled
    # return the 2 first parameters value
    if mode1 == 0:
        p1 = intcode[intcode[i+1]]
    elif mode1 == 1:
        p1 = intcode[i+1]
    
    if mode2 == 0:
        p2 = intcode[intcode[i+2]]
    elif mode2 == 1:
        p2 = intcode[i+2]
 
    return p1, p2


def read_intcode(intcode, _input):

    i = 0
    while i < len(intcode):

        opcode = intcode[i]%100
        mode1 = intcode[i]%1000//100
        mode2 = intcode[i]//1000
        para1 = para2 = None
        print()
        print("index, value : ", i, intcode[i])
        print("opcode, mode1, mode2 : ", opcode, mode1, mode2)
        
        if opcode == 99:
            return
 
        # opcode operations
        # add
        elif opcode == 1:
            print("add !")
            para1, para2 = get_mode(intcode, i, mode1, mode2)
            intcode[intcode[i+3]] = para1 + para2
            i += 4
        # multiply        
        elif opcode == 2: 
            print("multiply !")
            para1, para2 = get_mode(intcode, i, mode1, mode2)
            intcode[intcode[i+3]] = para1 * para2
            i += 4
        # store
        elif opcode == 3:
            print("store !")
            para1 = intcode[i+1]
            if i == 0:
                intcode[intcode[i+1]] = _input 
            i += 2
        # print
        elif opcode == 4:
            para1 = intcode[intcode[i+1]]
            print("Diag code = ",para1)
            i += 2
        # jump true
        elif opcode == 5:
            print("jump true !")
            para1, para2 = get_mode(intcode, i, mode1, mode2)
            if para1 != 0:
                i = para2
            else:
                i += 3 
        # jump false
        elif opcode == 6:
            print("jump false !")
            para1, para2 = get_mode(intcode, i, mode1, mode2)
            if para1 == 0:
                i = para2
            else:
                i += 3
        # less than
        elif opcode == 7:
            print("less than !")
            para1, para2 = get_mode(intcode, i, mode1, mode2)
            if para1 < para2:
                intcode[intcode[i+3]] = 1
            else:
                intcode[intcode[i+3]] = 0
            i += 4 
        # equal
        elif opcode == 8:
            print("equal")
            para1, para2 = get_mode(intcode, i, mode1, mode2)
            if para1 == para2:
                intcode[intcode[i+3]] = 1
            else:
                intcode[intcode[i+3]] = 0
            i += 4

        print("para1, para2 : ",para1, para2)
        

intcode = []

with open(path+'/input', 'r') as f:
    for l in f:
        for i in l.split(','):
            intcode.append(int(i))



print(len(intcode))
read_intcode(intcode, 5)
